In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Data/finalTrain.csv")

In [3]:
df.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min)
0,0xcdcd,DEHRES17DEL01,36.0,4.2,30.327968,78.046106,30.397968,78.116106,12-02-2022,21:55,22:10,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46
1,0xd987,KOCRES16DEL01,21.0,4.7,10.003064,76.307589,10.043064,76.347589,13-02-2022,14:55,15:05,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23
2,0x2784,PUNERES13DEL03,23.0,4.7,18.562450,73.916619,18.652450,74.006619,04-03-2022,17:30,17:40,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21
3,0xc8b6,LUDHRES15DEL02,34.0,4.3,30.899584,75.809346,30.919584,75.829346,13-02-2022,09:20,09:30,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20
4,0xdb64,KNPRES14DEL02,24.0,4.7,26.463504,80.372929,26.593504,80.502929,14-02-2022,19:50,20:05,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41

In [4]:
df_distance = df[["Restaurant_latitude","Restaurant_longitude","Delivery_location_latitude","Delivery_location_longitude"]]

In [5]:
df_distance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45584 entries, 0 to 45583
Data columns (total 4 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Restaurant_latitude          45584 non-null  float64
 1   Restaurant_longitude         45584 non-null  float64
 2   Delivery_location_latitude   45584 non-null  float64
 3   Delivery_location_longitude  45584 non-null  float64
dtypes: float64(4)
memory usage: 1.4 MB

In [6]:
df_distance.head()

,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude
0,30.327968,78.046106,30.397968,78.116106
1,10.003064,76.307589,10.043064,76.347589
2,18.562450,73.916619,18.652450,74.006619
3,30.899584,75.809346,30.919584,75.829346
4,26.463504,80.372929,26.593504,80.502929

In [11]:
columns = df_distance.columns
for i in columns:
    print(df_distance[i].unique())

[ 30.327968  10.003064  18.56245   30.899584  26.463504  19.176269
  12.311072  18.592718  17.426228  22.552672  18.563934  23.357804
  11.003669  12.986047  19.221315  13.005801  26.849596  21.160522
  12.934179  18.51421   11.022477  21.160437  15.51315   15.561295
   0.        18.55144   18.593481  21.173343  17.451976  12.972532
  13.064181  19.121999  21.149569  19.091458  22.539129  12.970324
  21.175975  23.369746  12.914264  11.003681  10.96185   27.165108
  26.88842   26.913987  12.3085    21.183434  19.254567  25.449659
  30.372202  12.972793  21.157735  21.186438  12.935662  17.431477
  12.933298  22.311358  12.934365  13.086438  26.913483  17.411028
  18.516216  15.5696    19.876428  12.939496  17.433809  23.374878
 -27.163303  22.74806   26.891191  12.316967  18.927584  11.022298
  12.325461  18.530963  17.458998  19.1813    22.727021  12.979166
  18.994237  12.284747  11.000762  26.479108  21.175104  12.975377
  23.359194  12.297954  23.359407  23.416792  26.892312  22.31279
  22.761593  11.026117  26.483042  23.359033  22.569358  21.157729
  22.311603  18.536562  22.745536  18.543626  17.41233   21.17106
  21.186884  19.065838  12.98041   12.310972  11.025083  22.538731
  11.001753  22.310237  22.725748  17.450851  13.081878  10.035573
  22.308096  12.975996  19.178321  26.910262  25.443994  12.321214
  19.055831  12.337928  23.351489  22.728163  13.026286  26.766536
  21.149834  21.149669  26.482581  26.911378  13.02978   12.323194
  22.569367  12.949934  22.725835  30.89286   12.933284  12.352058
  17.429585  12.978453  13.044694  26.846156  26.911927  10.020683
  15.585658  22.310526  19.103249  26.471617  19.866969  12.906229
  22.751857  11.010375  17.483216  27.160934  11.006686  25.457687
  19.12663   19.875016  18.536718  13.026279  17.455894  22.745049
  13.054347  12.979096  27.163303  26.482419  22.307898  27.160832
  10.027014  30.890184  21.15276   22.753839  19.876106  30.328174
  13.058616 -27.165108  21.170096  30.905562 -18.55144   26.902328
  26.90519   17.428294  12.323978  26.492106  19.003517  10.994136
  23.353783  17.440827  12.304569  12.299524  19.131141  19.879631
  18.520016  21.170798  22.760072  22.761226  23.354422  22.722634
  12.972161  22.526461  23.371292  13.029198  18.546258  26.921411
  11.008638  13.049645  17.430448  19.874733  13.045479  26.956431
  13.022394  22.75004   21.173493  13.091809  18.533811  15.496162
  26.913726  30.895817 -30.366322  12.323994  19.120083  12.337978
  27.161661  13.066762  30.362686  17.410371   9.979186  18.539299
  22.310329  11.022169  19.875908  10.006881  12.326356  19.875522
  22.552996  30.895204  25.450329  18.546947  30.340722  22.651847
  25.45235   17.424114  12.323225 -12.325461  26.905287  17.422819
  17.45971   22.695207  18.569156  11.003008  26.914142  30.359722
  12.334022  23.214294 -12.316967  12.970221  22.753659  18.636215
  22.751234  23.234249  25.457116  22.744648  23.39925   19.874103
  22.577821  22.514119  22.311844  18.994049  22.732225  30.914057
  23.233219  12.981615  23.184992  26.49095   22.551084  11.021278
  30.899992  11.024839  23.351058  19.876219  19.880256  13.027018
  30.893234  30.319528  27.195928 -23.359194  25.450317  21.185047
  23.355164  23.232537  17.431668  18.53408   26.902908  11.016298
  10.000706  25.454697  21.186608  26.90294   23.214459  12.913041
  23.374989  30.893244  30.885915  17.438263  15.544419  26.474986
   9.970717  30.873988  19.888716  22.547186  23.232357  23.234631
  19.1093    22.32     -26.47775   26.469003  26.483672  10.027364
 -15.546594  19.207222  19.874449 -12.337978  11.02091   19.22384
  30.366322  30.361281  26.473698  18.554382  22.553227 -27.160934
  30.332735   9.982834  15.498603  22.5491    25.450377  26.471529
 -26.90519   23.218998  23.235123  22.533662  30.885814 -17.45971
  15.574828  25.459775  30.893081  22.514688 -26.914142  23.266261
  23.333017 -19.176269  27.157772  15.516833  22.527893  27.159795
  15.546594  15.157944  27.16185   30.88722   27.158822 -23.230791
  23.264015  27.161694   9.991703  27.201725   9.960846  26.481547
 -22.539129  15.303897   9.988483  25.454648  30.342509 -15.157944
  22.53796   -9.959778  30.346994 -15.51315   15.49395  -27.16185
  11.001852  30.893384 -15.576683  19.875337 -18.520016  15.556561
  23.230791 -26.891191  15.56155   30.335259 -22.538999  26.47775
 -19.103249 -30.902872   9.985497  25.451517 -22.526461  26.472001
   9.959778  -9.988483 -23.211529  30.892978  15.506205  19.878028
 -30.895817 -26.474986  22.538999   9.957144  22.515082  25.451646
 -15.5696   -12.311072 -26.913987 -12.970324   9.979363  10.028047
 -21.157735 -23.374989 -13.049645  26.474133  30.902872   9.985697
 -26.913726  23.211529  19.876994 -22.310329 -23.234249  15.576683
  22.514585  25.449872  25.453436   9.966783 -25.45235  -17.451976
 -21.186884 -26.472001 -26.910262 -11.003681 -11.003669 -13.054347
 -30.372202 -12.972793 -25.449872 -18.569156 -18.546258 -17.429585
 -27.159795 -22.553227 -22.761593  -9.966783 -13.086438 -19.878028
 -17.440827  -9.970717 -12.913041 -12.970221 -19.876994 -19.875522
 -25.449659 -30.346994 -22.552672 -22.311603 -12.352058 -25.450317
 -21.15276  -12.949934 -26.49095  -25.443994 -30.319528 -10.028047
 -12.323978 -19.876106  26.47     -18.53408  -26.463504 -30.899584
 -22.311844 -17.438263 -23.39925  -23.234631 -30.361281 -19.091458
 -17.483216 -15.496162 -22.725835 -30.885915 -22.53796  -12.972161
 -23.184992 -17.424114 -10.035573 -19.22384  -23.235123 -25.453436
 -23.359033 -19.221315 -23.214459 -21.173343 -26.483042 -21.183434
 -22.310526 -22.74806  -12.304569 -19.1093   -19.879631 -19.874449
 -10.020683 -19.875337 -26.911927 -23.416792 -21.186608 -12.323994
 -12.933284 -17.450851 -19.875016 -22.569358 -12.284747 -23.355164
 -18.592718 -27.201725 -22.311358 -19.207222 -13.022394 -21.149569
 -22.538731 -27.161661 -27.160832 -13.066762 -10.96185  -12.935662
 -17.428294 -30.359722 -11.022169 -30.885814 -25.451517 -22.651847
 -22.547186 -26.474133 -30.893384 -22.761226 -11.001852 -30.327968
 -22.745536 -17.455894 -26.481547 -22.32     -23.371292 -18.563934
 -30.905562 -25.450377 -22.515082 -22.725748 -23.351058 -26.473698
 -23.333017 -30.873988  -9.982834 -22.514119 -21.170798 -12.979166
 -19.065838 -19.876428 -13.02978  -12.310972 -22.307898 -21.170096
 -21.186438  -9.960846 -10.994136 -21.175104 -15.303897 -11.022477
 -26.846156 -25.457116 -26.905287 -21.149834 -30.328174 -30.362686
 -19.055831 -22.5491   -26.471529 -12.934365 -30.893244 -19.888716
 -12.975377 -22.551084 -15.561295 -22.695207 -26.956431  -9.979186
 -11.006686 -12.323225 -13.026286 -25.454697 -23.357804 -19.880256
 -13.081878 -10.027014 -18.543626 -10.003064 -22.552996 -18.530963
 -19.866969 -22.75004  -26.469003 -26.766536 -12.326356 -22.577821
 -22.569367 -23.232357 -13.091809 -12.933298 -22.533662 -22.745049
 -26.921411 -23.374878 -27.158822 -12.906229 -13.044694 -13.045479
 -12.98041  -26.90294  -23.369746 -19.875908 -26.479108 -30.892978
 -23.232537 -22.514585 -22.751234 -17.426228 -17.411028 -18.636215
 -15.56155  -19.254567 -25.457687 -15.506205 -15.516833 -11.02091
 -12.3085   -26.47     -19.003517 -30.890184 -22.760072 -22.722634
 -19.12663  -22.753839 -21.173493 -17.430448 -12.939496 -18.56245
 -22.308096 -23.264015 -26.482581 -15.498603 -18.51421  -12.975996
 -19.874733 -15.49395  -12.978453]
[ 78.046106  76.307589  73.916619  75.809346  80.372929  72.836721
  76.654878  73.773572  78.407495  88.352885  73.915367  85.325146
  76.976494  80.218114  72.862381  80.250744  75.800512  72.771477
  77.615797  73.838429  76.995667  72.774209  73.78346   73.749478
   0.        73.804855  73.785901  72.792731  78.385883  77.608179
  80.236442  72.908493  72.772697  72.827808  88.365507  77.645748
  72.795503  85.33982   77.6784    76.975525  76.971082  78.015053
  75.800689  75.752891  76.665808  72.814492  72.848923  81.839744
  78.077151  80.249982  72.768778  72.794115  77.61413   78.40035
  77.614293  73.164798  77.616155  80.220672  75.803139  78.329645
  73.842527  73.742294  75.364792  77.625999  78.386744  85.335739
  78.057044  75.8934    75.802083  76.603067  72.832585  76.998349
  76.632278  73.828972  78.500366  72.836191  75.884167  77.640709
  72.825553  76.625861  76.981876  80.315042  72.804342  77.696664
  85.325447  76.665169  85.325055  85.316842  75.806896  73.170283
  75.886362  76.944652  80.317833  85.325347  88.433452  72.768726
  73.165012  73.896485  75.893106  73.905101  78.449654  72.789292
  72.793616  72.832658  77.640489  76.659264  77.015393  88.364878
  76.986241  73.158921  75.898497  78.379347  80.248519  76.336958
  73.167753  80.221898  72.834715  75.783013  81.860187  76.621094
  72.833984  76.617889  85.324253  75.884212  80.275235  75.837333
  72.778666  72.772629  80.315628  75.789034  80.208812  76.630583
  88.433187  77.699386  75.887648  75.822199  77.615428  76.60665
  78.392621  77.643685  80.26147   75.8023    75.797282  76.310631
  73.743606  73.170937  72.846749  80.313564  75.318894  77.596791
  75.866699  76.95295   78.552111  78.044095  76.951736  81.835585
  72.829976  75.322405  73.830327  80.174568  78.375467  75.892471
  80.257221  77.640625  80.320939  73.167788  78.011608  76.308053
  75.829615  72.778059  75.897429  75.340775  78.049117  80.264151
  72.789122  75.832841 -73.804855  75.794257  75.810753  78.404423
  76.627961  80.327797  72.82765   76.963303  85.326967  78.393391
  76.643622  76.64262   72.813074  75.323403  73.830547  72.790489
  75.892574  75.887522  85.3329    75.886959  77.596014  88.364453
  85.327872  77.570997  73.904337  75.793604  76.984311  80.242268
  78.418213  75.353942  80.23311   75.776649  80.242439  75.902847
  72.801953  80.219104  73.899315  73.825364  75.75282   75.813112
 -78.070453  76.626167  72.907385  76.616792  78.011544  80.251865
  78.06889   78.437225  76.317361  73.897902  73.169083  76.999594
  75.358888  76.345397  76.619103  75.367127  88.35231   75.822103
  81.834279  73.900626  78.060221  75.881991  81.841889  78.347554
  76.630028 -76.632278  75.794592  78.449578  78.368855  75.866059
  73.774723  76.97544   75.805704  78.067079  76.618203  77.435361
  77.645396  75.903365  73.751081  75.88949   77.434007  81.859682
  75.894377  85.390464  75.368419  88.400581  88.362504  73.165081
  72.825203  75.874765  75.83982   77.433571  80.231598  77.417227
  80.318656  88.354127  76.995017  75.831338  77.007003  85.325731
  75.346017  75.323503  80.254791  75.82172   78.040267  77.998092
 -85.325447  81.831681  72.80859   85.324097  77.429845  78.408321
  73.89852   75.792934  76.972076  76.349516  81.834492  72.794136
  75.793007  77.434976  77.683237  85.335486  75.821817  75.788259
  78.397865  73.755736  80.342796  76.285447  75.842739  75.321461
  88.35068   77.429989  77.401663  72.825451  73.17     -80.351569
  80.316344  80.320708  76.308258  73.760431  72.972281  75.360232
  76.940432  72.841347  78.070453  78.068022  80.352677  73.798206
  88.353273 -78.044095  78.054222  76.283268  73.826911  88.400467
  81.834236  80.313458 -75.810753  77.373573  77.398886  88.366217
  75.786976  73.766883  81.834841  75.821495  88.393294  77.379605
  85.3172   -72.836721  78.04725   73.768172  88.368628  78.04299
  73.950889  78.040165  75.804893  78.045359  77.43702   77.408236
  78.034714  76.293136  78.007553  76.293936  80.299775  73.914336
  76.295211  81.834502  78.061187  88.349843  76.296106  78.062543
  73.827423 -78.040165  76.976268  75.821202  73.75575   75.316722
 -73.830547  73.763633  73.749092  78.053162 -88.322337  80.351569
 -72.846749  75.826808  76.276999  81.832616  80.354002  77.419399
  75.821847  73.766668  75.317475  88.322337  76.296783  88.36783
  81.832796 -76.654878 -77.645748  76.285001  76.310019 -80.242268
  80.3481    76.281128  75.372353 -73.169083 -77.434007  88.39331
  81.836167  81.833167  76.242981 -81.841889 -78.385883 -75.783013
 -76.975525 -76.976494 -80.257221 -78.077151 -73.904337 -78.392621
 -78.04299  -75.367127 -78.062543 -88.352885 -76.60665  -77.699386
 -81.860187  80.35     -73.165081 -78.397865 -72.827808 -75.887648
 -85.335486 -77.596014 -78.347554 -72.841347 -72.862381 -72.792731
 -72.814492 -76.643622 -85.316842 -76.626167 -77.615428 -78.379347
 -76.625861 -73.164798 -72.972281 -77.683237 -78.011544 -80.251865
 -77.61413  -88.349843 -76.999594 -75.881991 -75.821202 -75.887522
 -76.976268 -78.375467 -73.17     -75.832841 -81.834236 -85.325731
 -85.3172   -76.283268 -77.640709 -78.068022 -80.208812 -72.789122
 -75.340775 -72.804342 -76.995667 -81.859682 -75.794592 -78.06889
 -76.963303 -77.616155 -77.696664 -75.866059 -76.951736 -76.630028
 -85.325146 -73.828972 -75.902847 -80.316344 -76.619103 -80.242439
 -76.293936 -77.614293 -88.366217 -75.837333 -75.892471 -75.793604
 -80.248519 -78.045359 -77.596791 -80.26147  -80.23311  -77.640489
 -80.220672 -75.793007 -85.33982  -78.407495 -73.773572 -76.603067
 -73.751081 -76.971082 -75.75282  -78.404423 -76.940432 -76.665808
 -73.742294 -77.43702  -75.829615 -72.772697 -75.897429 -80.318656
 -72.801953 -72.832658 -73.916619 -77.408236 -73.838429 -72.778059
 -73.827423 -77.643685]
[30.397968 10.043064 18.65245  ... 30.982872 15.636205 20.005337]
[78.116106 76.347589 74.006619 ... 75.906808 73.896668 75.446722]

In [12]:
import pandas as pd
import math
def distance(lat1,lon1, lat2,lon2):
    # Radius of the Earth in kilometers
    radius = 6371 

    lat1 = abs(lat1)
    lon1 = abs(lon1)
    lat2 = abs(lat2)
    lon2 = abs(lon2)


    # Convert latitude and longitude to radians
    lat1, lon1, lat2, lon2 = map(math.radians, [lat1,lon1,lat2,lon2])

    # Calculate the differences between the latitudes and longitudes
    dlat = lat2 - lat1
    dlon = lon2 - lon1

    # Calculate the Haversine formula
    a = math.sin(dlat/2)**2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon/2)**2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1-a))
    distance = radius * c

    return distance

In [13]:
df_distance["Distance"] = df_distance.apply(lambda row:distance(row['Restaurant_latitude'],row['Restaurant_longitude'],row['Delivery_location_latitude'],row['Delivery_location_longitude']),axis=1)

/tmp/ipykernel_406/900146278.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_distance["Distance"] = df_distance.apply(lambda row:distance(row['Restaurant_latitude'],row['Restaurant_longitude'],row['Delivery_location_latitude'],row['Delivery_location_longitude']),axis=1)

In [ ]:
"""

import geopy.distance
# Create a new column to store the distances
distances = []

# Loop through the restaurant and delivery location coordinates
for Resturant_Location, Delevery_Location in zip(df_copy["Resturant_Location"], df_copy["Delevery_Location"]):
    # Calculate the distance between the two locations
    distance = geopy.distance.distance(
        Resturant_Location,
        Delevery_Location,
    ).km

    # Add the distance to the distances list
    distances.append(distance)

"""

In [14]:
df_distance.head()

,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Distance
0,30.327968,78.046106,30.397968,78.116106,10.280582
1,10.003064,76.307589,10.043064,76.347589,6.242319
2,18.562450,73.916619,18.652450,74.006619,13.787860
3,30.899584,75.809346,30.919584,75.829346,2.930258
4,26.463504,80.372929,26.593504,80.502929,19.396618

In [15]:
df_distance.describe()

,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Distance
count,45584.000000,45584.000000,45584.000000,45584.000000,45584.000000
mean,17.017948,70.229684,17.465480,70.844161,9.735119
std,8.185674,22.885575,7.335562,21.120578,5.608034
min,-30.905562,-88.366217,0.010000,0.010000,1.465067
25%,12.933284,73.170000,12.988453,73.280000,4.663345
50%,18.551440,75.897963,18.633934,76.002574,9.220148
75%,22.728163,78.044095,22.785049,78.107044,13.681492
max,30.914057,88.433452,31.054057,88.563452,20.969489